# Generated by Django 4.1.13 on 2024-11-06 10:58

import django.contrib.postgres.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('AWS', 'AWS'), ('DOCKER', 'Docker'), ('GIT_GITHUB', 'Git & GitHub'), ('JENKINS', 'Jenkins'), ('KUBERNETES', 'Kubernetes'), ('LINUX', 'Linux')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('title_des', models.CharField(max_length=225)),
                ('link', models.URLField()),
                ('client', models.CharField(max_length=100)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('dev_type', models.CharField(choices=[('WEB_APP', 'Web App'), ('MOBILE_APP', 'Mobile App'), ('FRONTEND', 'Frontend'), ('BACKEND', 'Backend')], max_length=20)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
